import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import type { ActionStep, StepExpectation } from "@mobile-automation/shared";
import { describe, expect, it, vi } from "vitest";
import { StepExpectationPanel, expectationLabel } from "./StepExpectationPanel";

describe("StepExpectationPanel", () => {
  it("renders an empty state and expectation add actions", () => {
    const markup = renderPanel({
      id: "step-1",
      order: 1,
      type: "tap",
      enabled: true,
      params: {},
      createdAt: "2026-06-04T00:00:00.000Z"
    });

    expect(markup).toContain("预期验证");
    expect(markup).toContain("系统会默认检查崩溃和可响应");
    expect(markup).toContain("文字");
    expect(markup).not.toContain("无崩溃");
    expect(markup).not.toContain("应用可响应");
  });

  it("hides system guard expectations from manual editing", () => {
    const markup = renderPanel({
      id: "step-1",
      order: 1,
      type: "tap",
      enabled: true,
      params: {},
      expectations: [
        {
          id: "exp-crash",
          type: "no_crash",
          enabled: true,
          params: { autoGenerated: true },
          createdAt: "2026-06-04T00:00:00.000Z"
        },
        {
          id: "exp-alive",
          type: "app_alive",
          enabled: true,
          params: { autoGenerated: true },
          createdAt: "2026-06-04T00:00:00.000Z"
        }
      ],
      createdAt: "2026-06-04T00:00:00.000Z"
    });

    expect(markup).toContain("系统会默认检查崩溃和可响应");
    expect(markup).not.toContain("无崩溃/ANR");
    expect(markup).not.toContain("应用可响应");
  });

  it("renders text expectation OCR region fields and auto-generated advisory metadata", () => {
    const expectation: StepExpectation = {
      id: "exp-1",
      type: "text",
      enabled: false,
      params: {
        expected: "课堂已开始",
        mode: "contains",
        lang: "chi_sim",
        region: { x: 1, y: 2, width: 3, height: 4 },
        autoGenerated: true,
        reliability: "P1",
        blocking: false
      },
      note: "自动识别候选",
      createdAt: "2026-06-04T00:00:00.000Z"
    };
    const markup = renderPanel({
      id: "step-1",
      order: 1,
      type: "tap",
      enabled: true,
      params: {},
      expectations: [expectation],
      createdAt: "2026-06-04T00:00:00.000Z"
    });

    expect(markup).toContain("文字断言");
    expect(markup).toContain("课堂已开始");
    expect(markup).toContain("OCR 区域");
    expect(markup).toContain("候选 P1");
    expect(markup).toContain("建议");
  });

  it("labels expectation types", () => {
    expect(expectationLabel("no_crash")).toBe("无崩溃/ANR");
    expect(expectationLabel("text")).toBe("文字断言");
    expect(expectationLabel("metric_below")).toBe("指标阈值");
  });
});

function renderPanel(step: ActionStep): string {
  const noop = vi.fn();
  return renderToStaticMarkup(
    React.createElement(StepExpectationPanel, {
      step,
      stepIndex: 0,
      addStepExpectation: noop,
      updateStepExpectation: noop,
      removeStepExpectation: noop
    })
  );
}
