import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import type { ActionStep, StepExpectation } from "@mobile-automation/shared";
import { describe, expect, it, vi } from "vitest";
import {
  buildActionTargetPatchFromEvidence,
  buildStrongExpectationFromEvidence,
  StepList,
  summarizeStep
} from "./StepList.js";
import { expectationLabel } from "./StepExpectationPanel.js";

const noop = vi.fn();

describe("StepList", () => {
  it("renders an empty state before recording steps", () => {
    const markup = renderStepList([]);

    expect(markup).toContain("点击预览、返回、Home、输入或等待会生成步骤");
  });

  it("renders step actions and conditional tap editor", () => {
    const step = actionStep({
      id: "step-condition",
      order: 1,
      type: "tap_if_text",
      params: { text: "允许", mode: "contains", timeoutMs: 3000, intervalMs: 500 },
      coordinate: { x: 120, y: 240 },
      expectations: [expectation("text", { expected: "权限弹窗", mode: "contains", blocking: true })]
    });
    const markup = renderStepList([step]);

    expect(markup).toContain("tap_if_text");
    expect(markup).toContain("看到 &quot;允许&quot; 时点击 120, 240");
    expect(markup).toContain("插入条件点击");
    expect(markup).toContain("触发文字");
    expect(markup).toContain("文字断言");
    expect(markup).toContain("阻断");
  });

  it("renders text expectation editor with OCR region inputs", () => {
    const step = actionStep({
      expectations: [
        expectation("text", {
          expected: "课堂已开始",
          mode: "contains",
          lang: "chi_sim",
          region: { x: 1, y: 2, width: 300, height: 80 }
        })
      ]
    });
    const markup = renderStepList([step]);

    expect(markup).toContain("文字断言");
    expect(markup).toContain("contains &quot;课堂已开始&quot;");
    expect(markup).toContain("OCR 区域");
    expect(markup).toContain("value=\"300\"");
  });

  it("renders recorded steps as structured rule details", () => {
    const step = actionStep({
      type: "tap_on_element",
      params: {
        selector: "id=cn.eeo.classin:id/class_item",
        resourceId: "cn.eeo.classin:id/class_item",
        locator: {
          resourceId: "cn.eeo.classin:id/class_item",
          text: "高三一班"
        }
      },
      preconditions: [expectation("text", { expected: "我是教师", mode: "exists", resourceId: "cn.eeo.classin:id/tab_teacher" })],
      expectations: [
        expectation("text", { expected: "班级详情", mode: "contains", resourceId: "cn.eeo.classin:id/class_detail_title" }),
        expectation("screen_changed", { threshold: 0.12 }),
        expectation("no_crash", { blocking: true }),
        expectation("app_alive", { blocking: true })
      ]
    });

    const markup = renderStepList([step]);

    expect(markup).toContain("动作策略");
    expect(markup).toContain("tap_on_element");
    expect(markup).toContain("id=cn.eeo.classin:id/class_item");
    expect(markup).toContain("resourceId=cn.eeo.classin:id/class_item");
    expect(markup).toContain("text=高三一班");
    expect(markup).toContain("前置条件");
    expect(markup).toContain("元素存在");
    expect(markup).toContain("resourceId=cn.eeo.classin:id/tab_teacher");
    expect(markup).toContain("后置预期");
    expect(markup).toContain("文字断言 contains &quot;班级详情&quot;");
    expect(markup).toContain("画面变化");
    expect(markup).not.toContain("系统守护");
    expect(markup).not.toContain("无崩溃/ANR");
    expect(markup).not.toContain("应用可响应");
  });

  it("renders editable rule sections and keeps system guards implicit", () => {
    const step = actionStep({
      type: "tap_on_element",
      params: {
        selector: "id=cn.eeo.classin:id/login",
        resourceId: "cn.eeo.classin:id/login",
        text: "登录"
      },
      preconditions: [expectation("text", { expected: "登录", mode: "exists", resourceId: "cn.eeo.classin:id/login" })],
      expectations: [
        expectation("text", { expected: "首页", mode: "contains" }),
        expectation("no_crash", { autoGenerated: true }),
        expectation("app_alive", { autoGenerated: true })
      ]
    });

    const markup = renderStepList([step]);

    expect(markup).toContain("前置条件");
    expect(markup).toContain("添加前置条件");
    expect(markup).toContain("动作策略");
    expect(markup).toContain("tap_on_element");
    expect(markup).toContain("tap_on_text");
    expect(markup).toContain("后置预期");
    expect(markup).toContain("添加后置预期");
    expect(markup).toContain("强基准");
    expect(markup).toContain("建议");
    expect(markup).not.toContain("系统守护");
    expect(markup).not.toContain("预期验证");
    expect(markup).not.toContain("无崩溃/ANR");
    expect(markup).not.toContain("应用可响应");
  });

  it("keeps graph asset debug details out of recorded rule cards", () => {
    const step = actionStep({
      params: {
        graphAsset: {
          status: "skipped",
          warnings: [
            {
              code: "UI_DUMP_FAILED",
              message: "Command failed: adb shell uiautomator dump /sdcard/window.xml"
            }
          ]
        }
      }
    });

    const markup = renderStepList([step]);

    expect(markup).toContain("动作策略");
    expect(markup).not.toContain("图谱资产");
    expect(markup).not.toContain("Command failed");
    expect(markup).not.toContain("adb shell uiautomator");
    expect(markup).not.toContain("当前步骤未写入业务图谱");
    expect(markup).not.toContain("未知起点");
    expect(markup).not.toContain("未知终点");
  });

  it("renders recording evidence candidates as selectable baselines", () => {
    const step = actionStep({
      type: "tap_on_element",
      params: {
        recordingContext: {
          beforeObservation: {
            capturedAt: "2026-06-09T00:00:00.000Z",
            platform: "android",
            activityName: "cn.eeo.classin.MainActivity",
            uiElementCount: 12,
            ocrTextCount: 3,
            resourceIds: ["cn.eeo.classin:id/teacher_tab"],
            texts: ["我是教师"],
            contentDescriptions: ["course Photo"],
            classNames: ["android.widget.TextView"],
            elementCandidates: [
              {
                resourceId: "cn.eeo.classin:id/teacher_tab",
                text: "我是教师",
                contentDesc: "teacher tab",
                className: "android.widget.TextView",
                clickable: true,
                bounds: { x: 10, y: 20, width: 120, height: 44 }
              }
            ],
            textCandidates: [{ text: "我是教师", confidence: 0.92, region: { x: 8, y: 16, width: 130, height: 48 }, source: "ocr" }]
          },
          afterObservation: {
            capturedAt: "2026-06-09T00:00:01.000Z",
            platform: "android",
            activityName: "cn.eeo.classin.ClassDetailActivity",
            uiElementCount: 16,
            ocrTextCount: 4,
            resourceIds: ["cn.eeo.classin:id/class_detail_title"],
            texts: ["班级详情"],
            contentDescriptions: ["发布活动"],
            classNames: ["android.widget.TextView"],
            elementCandidates: [
              {
                resourceId: "cn.eeo.classin:id/class_detail_title",
                text: "班级详情",
                className: "android.widget.TextView",
                bounds: { x: 22, y: 30, width: 220, height: 52 }
              }
            ],
            textCandidates: [{ text: "班级详情", confidence: 0.88, region: { x: 20, y: 26, width: 230, height: 60 }, source: "ocr" }]
          }
        }
      }
    });

    const markup = renderStepList([step]);

    expect(markup).toContain("动作前采集");
    expect(markup).toContain("动作后采集");
    expect(markup).toContain("可选为强基准");
    expect(markup).toContain("resource-id");
    expect(markup).toContain("content-desc");
    expect(markup).toContain("OCR 文字");
    expect(markup).toContain("用作动作目标");
    expect(markup).toContain("设为强前置");
    expect(markup).toContain("设为强后置");
    expect(markup).toContain("cn.eeo.classin:id/teacher_tab");
    expect(markup).toContain("cn.eeo.classin:id/class_detail_title");
  });
});

describe("StepList helpers", () => {
  it("summarizes common step types", () => {
    expect(summarizeStep(actionStep({ type: "tap", coordinate: { x: 10, y: 20 } }))).toBe("10, 20");
    expect(summarizeStep(actionStep({ type: "tap_on_element", params: { selector: "id=com.demo:id/join_class" } }))).toBe(
      "点击元素 id=com.demo:id/join_class"
    );
    expect(summarizeStep(actionStep({ type: "swipe", coordinate: { startX: 1, startY: 2, endX: 3, endY: 4 } }))).toBe("1,2 -> 3,4");
    expect(summarizeStep(actionStep({ type: "input_text", params: { text: "hello" } }))).toBe("hello");
    expect(summarizeStep(actionStep({ type: "recent_apps" }))).toBe("打开最近任务");
  });

  it("labels expectation types", () => {
    expect(expectationLabel("text")).toBe("文字断言");
    expect(expectationLabel("image")).toBe("图像基准");
    expect(expectationLabel("metric_below")).toBe("指标阈值");
  });

  it("builds blocking expectations from selected recording evidence", () => {
    expect(
      buildStrongExpectationFromEvidence(
        {
          kind: "activity",
          label: "Activity",
          value: "cn.eeo.classin.ClassDetailActivity",
          source: "activity"
        },
        "after"
      )
    ).toMatchObject({
      type: "text",
      enabled: true,
      params: {
        activityName: "cn.eeo.classin.ClassDetailActivity",
        mode: "exists",
        blocking: true,
        source: "recording_evidence_after_activity"
      }
    });

    expect(
      buildStrongExpectationFromEvidence(
        {
          kind: "element",
          label: "resource-id",
          value: "cn.eeo.classin:id/class_detail_title",
          source: "element",
          candidate: {
            resourceId: "cn.eeo.classin:id/class_detail_title",
            text: "班级详情",
            className: "android.widget.TextView"
          }
        },
        "after"
      )
    ).toMatchObject({
      type: "text",
      enabled: true,
      params: {
        mode: "exists",
        resourceId: "cn.eeo.classin:id/class_detail_title",
        expected: "班级详情",
        className: "android.widget.TextView",
        blocking: true
      }
    });

    expect(
      buildStrongExpectationFromEvidence(
        {
          kind: "ocr_text",
          label: "OCR 文字",
          value: "班级详情",
          source: "ocr",
          textCandidate: {
            text: "班级详情",
            confidence: 0.88,
            region: { x: 20, y: 26, width: 230, height: 60 }
          }
        },
        "after"
      )
    ).toMatchObject({
      type: "text",
      enabled: true,
      params: {
        expected: "班级详情",
        mode: "contains",
        region: { x: 20, y: 26, width: 230, height: 60 },
        blocking: true
      }
    });
  });

  it("builds action target patches from selected element and text evidence", () => {
    expect(
      buildActionTargetPatchFromEvidence({
        kind: "element",
        label: "resource-id",
        value: "cn.eeo.classin:id/teacher_tab",
        source: "element",
        candidate: {
          resourceId: "cn.eeo.classin:id/teacher_tab",
          text: "我是教师",
          contentDesc: "teacher tab",
          className: "android.widget.TextView"
        }
      })
    ).toMatchObject({
      type: "tap_on_element",
      params: {
        selector: "id=cn.eeo.classin:id/teacher_tab",
        resourceId: "cn.eeo.classin:id/teacher_tab",
        text: "我是教师",
        contentDesc: "teacher tab",
        locator: {
          resourceId: "cn.eeo.classin:id/teacher_tab",
          text: "我是教师",
          contentDesc: "teacher tab",
          className: "android.widget.TextView"
        }
      }
    });

    expect(
      buildActionTargetPatchFromEvidence({
        kind: "ocr_text",
        label: "OCR 文字",
        value: "我是教师",
        source: "ocr",
        textCandidate: { text: "我是教师", confidence: 0.92 }
      })
    ).toMatchObject({
      type: "tap_on_text",
      params: {
        text: "我是教师",
        mode: "contains"
      }
    });
  });
});

function renderStepList(steps: ActionStep[]): string {
  return renderToStaticMarkup(
    React.createElement(StepList, {
      steps,
      moveStep: noop,
      removeStep: noop,
      insertWaitStep: noop,
      insertConditionalTapStep: noop,
      copyStep: noop,
      toggleStepEnabled: noop,
      updateStep: noop,
      addStepExpectation: noop,
      updateStepExpectation: noop,
      removeStepExpectation: noop
    })
  );
}

function actionStep(overrides: Partial<ActionStep> = {}): ActionStep {
  return {
    id: "step-1",
    order: 1,
    type: "tap",
    enabled: true,
    params: {},
    coordinate: { x: 100, y: 200 },
    expectations: [],
    createdAt: "2026-06-09T00:00:00.000Z",
    ...overrides
  };
}

function expectation(type: StepExpectation["type"], params: Record<string, unknown>): StepExpectation {
  return {
    id: `expectation-${type}`,
    type,
    enabled: true,
    params,
    createdAt: "2026-06-09T00:00:00.000Z"
  };
}
